server:
  port: 520

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.201.36.172/byzhDB?serverTimezone=UTC
    username: super
    password: "!@#BYzh21"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


